### ISSUE TITLE
Suggestion: Grey-out skill instead of hide

### ISSUE THREAD

**Issue by ghost** [robrichardson13/skills-organizer#1]
I've been looking for months for a plugin that's similar to this one, however with the ability to grey-out a skill instead of hiding them. I'm playing skill-restricted accounts (an 807-UIM for example) and it would be super awesome if it would be possible to grey-out the skills I'm "not allowed" to skill instead of hiding them.

Like the way F2P greys out the member skills.

<img width="218" alt="Scherm­afbeelding 2022-11-11 om 11 05 18" src="https://user-images.githubusercontent.com/2943720/201317051-7563cd58-ce69-4c90-993b-4005550a8487.png">

I think the plugin has the basics for this already but I'm not a good enough coder to modify it myself so I'm really hoping you're willing to add this feature to the plugin. I also think it might make the plugin appeal to a wider audience.

Hope to hear from you!

**Comment by robrichardson13** [comment]
Added in v1.1, waiting for approval here: https://github.com/runelite/plugin-hub/pull/3841
